<?php /* @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Radio */ ?>
<?php $_option = $this->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $this->_getDefaultValues(); ?>
<dt>
    <label id="label-attribute-ipad_abonnementsvorm" <?php if ($_option->getRequired()) echo ' class="required"' ?>><?php echo $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<em>&nbsp;</em>' ?></label>
</dt>
<?php $_attributeCode = 'ipad_abonnementsvorm'; ?>
<?php $_tooltipText = $this->getLayout()->createBlock('cms/block')->setBlockId('attribute_' . $_attributeCode)->toHtml(); ?>
<?php if ($_tooltipText): ?>
    <div style="display: none;" id="attribute-tooltip-<?php echo $_attributeCode; ?>"><?php echo $_tooltipText; ?></div>
    <script type="text/javascript">
        new Tip('label-attribute-<?php echo $_attributeCode; ?>', $('attribute-tooltip-<?php echo $_attributeCode; ?>'), {
            closeButton: true,
            showOn: 'click',
            width: 400
        });
    </script>
<?php endif; ?>

<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <div class="input-box">
    <?php if ($this->_showSingle()): ?>
        <?php echo $this->getSelectionTitlePrice($_selections[0]) ?>
        <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>" />
    <?php else:?>
        <ul class="options-list">
        <?php if (!$_option->getRequired()): ?>
            <li><input type="radio" onclick="bundle.changeSelection(this)" class="radio" id="bundle-option-<?php echo $_option->getId() ?>" name="bundle_option[<?php echo $_option->getId() ?>]"<?php echo ($_default && $_default->isSalable())?'':' checked="checked" ' ?> value=""/>
            <span class="label"><label for="bundle-option-<?php echo $_option->getId() ?>"><?php echo $this->__('None') ?></label></span>
            </li>
        <?php endif; ?>
        <?php foreach ($_selections as $_selection): ?>
            <?php $_product = Mage::getModel('catalog/product')->load($_selection->getProductId()); ?>
            <li class="product-abonnement-<?php echo $_product->formatUrlKey($_product->getAttributeText('ipad_titel')); ?>">
                <?php $_maandbedrag = Mage::helper('core')->formatPrice($_product->getIpadMaandbedrag(), false); ?>
                <?php $_voordeel = preg_replace('/[.,]00/', '', Mage::helper('core')->formatPrice($_product->getIpadVoordeel(), false)); ?>
                <?php $_image = $this->helper('catalog/image')->init($_product, 'image')->keepFrame(false)->constrainOnly(true)->resize(500, 675); ?>
                <input type="radio" onclick="bundle.changeSelection(this); ipadUpdateSummary('<?php echo addslashes($_maandbedrag); ?>', '<?php echo addslashes($_voordeel); ?>', '<?php echo addslashes($_image); ?>');" class="radio<?php echo $_option->getRequired()?' validate-one-required-by-name':'' ?> change-container-classname" id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>" name="bundle_option[<?php echo $_option->getId() ?>]"<?php if ($this->_isSelected($_selection)) echo ' checked="checked"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>value="<?php echo $_selection->getSelectionId() ?>"/>
                <span class="label">
                    <label for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>"><?php echo $this->getSelectionTitlePrice($_selection) ?></label><small><b><?php echo $_maandbedrag ?> per maand</b></small>
                </span>
                <?php if ($_option->getRequired()): ?>
                    <?php echo $this->setValidationContainer('bundle-option-'.$_option->getId().'-'.$_selection->getSelectionId(), 'bundle-option-'.$_option->getId().'-container') ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
        <div id="bundle-option-<?php echo $_option->getId() ?>-container"></div>
    <?php endif; ?>
    </div>
    <?php /*
    <span class="qty-holder">
        <label for="bundle-option-<?php echo $_option->getId() ?>-qty-input"><?php echo $this->__('Qty:') ?>&nbsp;</label><input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)" <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?> id="bundle-option-<?php echo $_option->getId() ?>-qty-input" class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>" type="text" name="bundle_option_qty[<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>"/>
    </span>
    */ ?>
    <input type="hidden" id="bundle-option-<?php echo $_option->getId() ?>-qty-input" name="bundle_option_qty[<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>"/>
</dd>
