<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view product-view-abonnement">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="product-shop  product-shop-options">
            <div class="product-shop-header">
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>

                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if ($_product->getShortDescription()):?>
                    <div class="short-description">
                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    </div>
                <?php endif;?>
            </div>

            <div class="product-options">
                <div class="buy-label">&nbsp;</div>
                <dl>
                    <dt class="product-step-1"><label id="label-attribute-ipad_titel"><?php echo $this->__('Titel')?><em>&nbsp;</em></label></dt>

                    <?php $_attributeCode = 'ipad_titel'; ?>
                    <?php $_tooltipText = $this->getLayout()->createBlock('cms/block')->setBlockId('attribute_' . $_attributeCode)->toHtml(); ?>
                    <?php if ($_tooltipText): ?>
                        <div style="display: none;" id="attribute-tooltip-<?php echo $_attributeCode; ?>"><?php echo $_tooltipText; ?></div>
                        <script type="text/javascript">
                            new Tip('label-attribute-<?php echo $_attributeCode; ?>', $('attribute-tooltip-<?php echo $_attributeCode; ?>'), {
                                closeButton: true,
                                showOn: 'click',
                                width: 400
                            });
                        </script>
                    <?php endif; ?>
                    <dd>
                        <div class="input-box">
                            <ul class="options-list product-abonnement-list">
                                <li>
                                    <input type="radio" class="radio" id="product-abonnement-noordhollands-dagblad" name="product-abonnement">
                                    <span class="label"><label for="product-abonnement-noordhollands-dagblad">Noordhollands Dagblad</label></span>
                                </li>
                                <li>
                                    <input type="radio" class="radio" id="product-abonnement-haarlems-dagblad" name="product-abonnement">
                                    <span class="label"><label for="product-abonnement-haarlems-dagblad">Haarlems Dagblad</label></span>
                                </li>
                                 <li>
                                    <input type="radio" class="radio" id="product-abonnement-ijmuider-courant" name="product-abonnement">
                                    <span class="label"><label for="product-abonnement-ijmuider-courant">IJmuider Courant</label></span>
                                </li>
                                <li>
                                    <input type="radio" class="radio" id="product-abonnement-leidsch-dagblad" name="product-abonnement">
                                    <span class="label"><label for="product-abonnement-leidsch-dagblad">Leidsch Dagblad</label></span>
                                </li>
                                <li>
                                    <input type="radio" class="radio" id="product-abonnement-de-gooi-en-eemlander" name="product-abonnement">
                                    <span class="label"><label for="product-abonnement-de-gooi-en-eemlander">De Gooi- en Eemlander</label></span>
                                </li>
                            </ul>
                        </div>
                    </dd>
                </dl>
            </div>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>

            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

            <script type="text/javascript">
                var step = 1;
                $$('.product-shop dt').each(function(el) {
                    el.addClassName('product-step-' + step);
                    step++;
                });
            </script>
            
            <?php 
            $subscription = false;
            if (Mage::getSingleton('customer/session')->isLoggedIn()){
	            $customer = Mage::getSingleton('customer/session')->getCustomer();
	            $subscriptionProduct = $customer->findSubscriptionProduct();
	            if ($subscriptionProduct) {
					$subscription = true;
				}
            }
            ?>

            <script type="text/javascript">
                $$('.product-abonnement-list input').each(function(el) {
                    el.observe('change', function(el2) {
                        ipadDisableAbonnementProducts();
                    });
                    el.observe('click', function(el2) {
                        ipadDisableAbonnementProducts();
                    });
                });
                function ipadDisableAbonnementProducts() {
                    $$('.product-abonnement-list input').each(function(el3) {
                        if (el3.checked) {
                            $$('.' + el3.id).invoke('show');
                        } else {
                            $$('.' + el3.id).invoke('hide');
                        }
                    });
                    $$('.product-abonnement-list input').each(function(el3) {
                        if (el3.checked) {
                            <?php
                            // In case of customer login, then select the subscription
                            if ($subscription):
	                           if($subscriptionProduct->getData('ipad_abonnementsvorm') == '127'){ ?>
	                           		$$('.' + el3.id + ' input') [1].checked = 'checked';
	                           		$$('.' + el3.id + ' input') [1].simulate('click');
		                    <?php     		   	
	                           } else {
							?>
	                           $$('.' + el3.id + ' input').first().checked = 'checked';
	                           $$('.' + el3.id + ' input').first().simulate('click');
	                        <?php } ?>   
                            <?php else:?>				
                            $$('.' + el3.id + ' input').first().checked = 'checked';
                            $$('.' + el3.id + ' input').first().simulate('click');
                            <?php endif;?>
                        }
                    });
                }
                function ipadUpdateSummary(maandbedrag, voordeel, image) {
                    $('ipad-maandbedrag').update(maandbedrag);
                    $('ipad-voordeel').update(voordeel);
                    $('product-image').src = image;
                }
                document.observe("dom:loaded", function() {
					<?php 
						// In case of customer login, then select the subscription
						if ($subscription):
					?>	
						$('product-abonnement-<?php echo $subscriptionProduct->formatUrlKey($subscriptionProduct->getAttributeText('ipad_titel'))?>').checked = true;
					<?php else:?>
	                    $$('.product-abonnement-list input').first().checked = true;
					<?php endif;?>	
                    
                    ipadDisableAbonnementProducts();
                });
            </script>
        </div>

        <div class="clearer"></div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>

</div>
