<?php
/**
 * @var $this Mage_Sales_Block_Order_Totals
 * @see Mage_Sales_Block_Order_Totals
 */
?>

	<tr>
		<td align="right"><strong><?php echo $this->__('Verzekerde levering aan huis')?></strong></td>
		<td align="right" style="padding:3px 9px">&euro; 9,95</td>
	</tr>
<?php foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getCode() == 'grand_total_incl'): ?>
        <?php if ($_total->getBlockName()): ?>
            <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
        <?php else:?>
        <tr class="<?php echo $_code?>">
            <td <?php echo $this->getLabelProperties()?>>
                <?php if ($_total->getStrong()):?>
                <strong><?php echo $_total->getLabel()?></strong>
                <?php else:?>
                <?php echo $_total->getLabel()?>
                <?php endif?>
            </td>
            <td <?php echo $this->getValueProperties()?>>
                <?php if ($_total->getStrong()):?>
                <strong><?php echo $this->formatValue($_total) ?></strong>
                <?php else:?>
                <?php echo $this->formatValue($_total) ?>
                <?php endif?>
            </td>
        </tr>
        <?php endif?>
    <?php endif; ?>
<?php endforeach?>